{{- if .Values.ingress.gateway }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ default .Release.Name .Values.ingress.name }}-gateway-{{ .Values.ingress.gateway.type }}
spec:
  selector:
    app: {{ .Values.ingress.gateway.gateway_selector }}
  servers:
    {{- range .Values.ingress.gateway.ports }}
    - port:
        number: {{ .number }}
        name: {{ .name }}
        protocol: {{ .protocol }}
    {{- if .tls }}
      tls:
        {{- toYaml .tls | nindent 8 }}
      {{- end }}
      hosts:
        {{- toYaml $.Values.ingress.hosts | nindent 8 }}
    {{- end }}
{{- end }}
