ingress:
  # name: git
  # hosts:
  #   - git.some.domain
  #   - git.some2.domain
  # gateway:
  #   type: ingress
  #   gateway_selector: "istio-ingress-gateway"
  #   ports:
  #     - number: 443
  #       name: https
  #       protocol: HTTP
  #       tls:
  #         mode: SIMPLE # enables HTTPS on this port
  #         serverCertificate: /etc/certs/servercert.pem
  #         privateKey: /etc/certs/privatekey.pem
  #     - number: 80
  #       name: http
  #       protocol: HTTP

  virtualservice:
    # gateways:
    #   - istio-ingress-gateway
    # http:
    #   - match:
    #       - uri:
    #           prefix: /health
    #     rewrite:
    #       uri: /healthz/ready
    #     route:
    #       - destination:
    #           host: istio-ingress-gateway
    #           port:
    #             number: 15021
    #   - match:
    #       - uri:
    #           prefix: "/"
    #     route:
    #       - destination:
    #           host: htpbin.default.svc.cluster.local
    #           port:
    #             number: 3000
    # tcp:
    # - match:
    #   - port: 27017
    #   route:
    #   - destination:
    #       host: mongo.backup.svc.cluster.local
    #       port:
    #         number: 5555

egress:
  # name: google
  # hosts:
  #   - www.google.com
  #   - google.ru
  # ports:
  #   - number: 443
  #     name: https
  #     protocol: HTTP
  #   - number: 80
  #     name: http
  #     protocol: HTTP
  # location: MESH_EXTERNAL
  # resolution: DNS

destinationrule:
  # name: my-service
  # host: my-service
  # trafficPolicy:
  #   loadBalancer:
  #     simple: RANDOM
  # subsets:
  #   - name: v1
  #     labels:
  #       version: v1
  #   - name: v2
  #     labels:
  #       version: v2
  #     trafficPolicy:
  #       loadBalancer:
  #         simple: ROUND_ROBIN
  #   - name: v3
  #     labels:
  #       version: v3
