{{- if .Values.egress }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ default .Release.Name .Values.egress.name }}-egress
spec:
  hosts:
    {{- toYaml .Values.egress.hosts | nindent 4 }}
  ports:
  {{- range .Values.egress.ports }}
    - port:
      number: {{ .number }}
      name: {{ .name }}
      protocol: {{ .protocol }}
  {{- end }}
{{- if .Values.egress.location }}
  location: {{ .Values.egress.location }}
{{- end  }}
{{- if .Values.egress.resolution }}
  resolution: {{ .Values.egress.resolution }}
{{- end  }}
{{- end }}
