{{- if .Values.ingress.virtualservice }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ default .Release.Name .Values.ingress.name }}-virtualservice
spec:
  hosts:
    {{- toYaml .Values.ingress.hosts | nindent 4 }}
  gateways:
{{- if and .Values.ingress.gateway .Values.ingress.gateway.type }}
    - {{ default .Release.Name .Values.ingress.name }}-gateway-{{ .Values.ingress.gateway.type }}
{{- else if and .Values.ingress.virtualservice .Values.ingress.virtualservice.gateways }}
{{- range .Values.ingress.virtualservice.gateways }}
    - {{ .  }}
{{- end }}
{{- end }}
{{- if and .Values.ingress.virtualservice .Values.ingress.virtualservice.http }}
  http:
    {{- toYaml .Values.ingress.virtualservice.http | nindent 4 }}
{{- end }}
{{- if and .Values.ingress.virtualservice .Values.ingress.virtualservice.tcp }}
  tcp:
    {{- toYaml .Values.ingress.virtualservice.tcp | nindent 4 }}
{{- end }}
{{- end }}
